import { Button, VerticalBox, LineEdit, TextEdit } from "std-widgets.slint";

export component AppWindow inherits Window {
    title: "Blog App";
    width: 1280px;
    height: 720px;
    background: @linear-gradient(300deg, #000080 0%, #87CEEB 33%, #565B59 66%, #000000 100%);

    GridLayout {
        padding: 50px;
        spacing: 25px;
        Row {
            Text {
                text: "Personal Blog";
                horizontal-alignment: center;
                font-weight: 10000;
                font-size: 32px;
            }
        }
        Row {
            TextEdit {
                text: "Enter your blog post here";
                horizontal-alignment: left;
                font-size: 18px;
                height: 200px;
            }
        }
        Row {
            Button {
                text: "Post";
                primary: false;
                height: 35px;
                clicked => { self.text = "Posted!"; }
            }
        }
    }
    }

