import { Button, VerticalBox, LineEdit, TextEdit } from "std-widgets.slint";

export component AppWindow inherits Window {
    
    in property <string> postText: "";
    callback posted(string);

    title: "Blog App";
    width: 1280px;
    height: 720px;
    background: @linear-gradient(300deg, #000080 0%, #87CEEB 33%, #565B59 66%, #000000 100%);

    GridLayout {
        padding: 20px;
        spacing: 20px;
        Row {
            Text {
                text: "Personal Blog";
                horizontal-alignment: center;
                font-weight: 10000;
                font-size: 32px;
            }
        }
        Row {
            VerticalBox {
                height: 300px;
                Rectangle {
                    background: @linear-gradient(60deg, #35343230 0%, #727e722f 33%, #727e722f 66%, #35343230 100%);
                    finishedPost := TextEdit {
                        text: postText;
                        horizontal-alignment: left;
                        font-size: 24px;
                        read-only: true;
                    }
                }
            }
        }
        Row {
            post := TextEdit {
                text: "Enter your blog post here";
                horizontal-alignment: left;
                font-size: 18px;
                height: 200px;
            }
        }
        Row {
            Button {
                text: "Post";
                primary: false;
                height: 35px;
                clicked => { posted(post.text) }
            }
        }
    }
    }

