import { Button, VerticalBox } from "std-widgets.slint";

export component AppWindow inherits Window {
    title: "Blog App";
    width: 1280px;
    height: 720px;
    background: navy;

    Rectangle {
        x: parent.width / 4;
        y: parent.height / 6;
        background: black;
        width: parent.width / 2;
        height: parent.height / 2;

        Rectangle {
            background: white;
            x: parent.width / 3;
            y: parent.height / 3;
            width: parent.width / 4;
            height: parent.height / 4;
            Button {
                text: "Create post";
            }
        }
    }
    }

